linters:
  black:
    config: ./pyproject.toml
    fixer: true
  flake8:
    python: 3
    fixer: true
    # copied from tox.ini
    max-complexity: 15
    ignore: W,E
    exclude: .venv, .git, __pycache__, dist
fixers:
  enable: true
