linters:

  black:
    config: ./pyproject.toml
    fixer: true

  flake8:
    fixer: true
    python: 3
    
    # copied from .flake8
    max-complexity: 15
    ignore: W,E
    exclude: .venv, venv, .git, __pycache__, dist, data

fixers:
  enable: true
