[Settings]
ID = "pokeapi"

[build]
publish = "dist"
command = "pip install poetry && poetry install --no-dev && poetry run ditto transform \"--base-url=$BASE_URL\""

[build.environment]
BASE_URL = "https://pokeapi.netlify.com/"

[[redirects]]
from = "/api/v2/:endpoint/"
to = "https://pokeapi.co/api/v2/:endpoint/?limit=:limit"
status = 301
force = true
query = {limit = ":limit"}

[[redirects]]
from = "/*/"
to = "/:splat/index.json"
status = 301
