[Settings]
ID = "pokeapi"

[build]
publish = "dist"
command = "pip install poetry && poetry install --no-dev && poetry run ditto transform \"--base-url=$BASE_URL\""

[build.environment]
BASE_URL = "https://pokeapi.netlify.com/"

[[redirects]]
from = "/*/"
to = "/:splat/index.json"
status = 200
