#!/usr/bin/env python3

import sys, requests, os, os.path, json

def safe_open_w(path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    return open(path, "w")

def print_json(data, path):
    print(json.dumps(data, indent=4, sort_keys=True), file=safe_open_w(path))

# Config

if len(sys.argv) != 3:
    print('Usage: ' + sys.argv[0] + ' <baseUrl> <targetDir>', file=sys.stderr)
    quit(1)

baseUrl = sys.argv[1]
targetDir = sys.argv[2]

if (not baseUrl.endswith("/")):
    baseUrl = baseUrl + "/"

if (not targetDir.endswith("/")):
    targetDir = targetDir + "/"

# Root

url = baseUrl + "api/v2/"
endpoints = requests.get(url)

path = targetDir + url.replace(baseUrl, '') + "index.json"
print(path)
print_json(endpoints.json(), path)

# Endpoints

for endpoint in endpoints.json().values():
    # Default index
    url = endpoint
    resourcelist = requests.get(url)
    path = targetDir + endpoint.replace(baseUrl, '') + "index.json"
    print(path)
    print_json(resourcelist.json(), path)
    
    # Fifty index
    url = endpoint + "?limit=50"
    resourcelist = requests.get(url)
    path = targetDir + endpoint.replace(baseUrl, '') + "limit=50.json"
    print(path)
    print_json(resourcelist.json(), path)

    # Zero index    
    url = endpoint + "?limit=0"
    resourcelist = requests.get(url)
    path = targetDir + endpoint.replace(baseUrl, '') + "limit=0.json"
    print(path)
    print_json(resourcelist.json(), path)
    
    # All index
    count = str(resourcelist.json()["count"])
    url = endpoint + "?limit=" + count
    resourcelist = requests.get(url)
    path = targetDir + endpoint.replace(baseUrl, '') + "limit=" + count + ".json"
    print(path)
    print_json(resourcelist.json(), path)
    
    # All resources
    for resourceSummary in resourcelist.json()['results']:
        resourceUrl = resourceSummary['url']
        path = targetDir + resourceUrl.replace(baseUrl, '') + "index.json"
        
        if not os.path.isfile(path):
            print(path)
            resource = requests.get(resourceUrl)
            print_json(resource.json(), path)
        
        if endpoint.endswith("/pokemon/"):
            resourceUrl = resourceUrl + "encounters/"
            path = targetDir + resourceUrl.replace(baseUrl, '') + "index.json"
            if not os.path.isfile(path):
                print(path)
                resource = requests.get(resourceUrl)
                print_json(resource.json(), path)








