version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - checkout
      - run:
          name: Display Python version
          command: python3 -V
      - run:
          name: Install deps
          command: |
            pip3 install poetry
            poetry install
      - run:
          name: Lint code
          command: poetry run black pokeapi_ditto
      - run:
          name: Spin up Pokeapi
          command: |
            git clone --recurse-submodules https://github.com/PokeAPI/pokeapi.git
            cd pokeapi
            make docker-setup
            cd ..
      - run:
          name: Clone
          command: poetry run ditto clone --dest-dir ./data
      - run:
          name: Analyze
          command: poetry run ditto analyze --data-dir ./data
      - run:
          name: Transform
          command: |
            poetry run ditto transform \
            --base-url='https://pokeapi.co' \
            --src-dir=./data \
            --dest-dir=./_gen

workflows:
  version: 2
  test:
    jobs:
      - test
